from_latest_tag = true
ignore_merge_commits = true
tag_prefix = "v"

post_bump_hooks = [
  "git push",
  "git push --tags",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "cognitodemo"
owner = "victormf2"

[monorepo.packages.a]
path = "a"
include = ["a/**"]
public_api = true
bump_order = 1
post_bump_hooks = [
  "cd a && go mod tidy",
  "git add a/go.mod a/go.sum",
]

[monorepo.packages.b]
path = "b"
include = ["b/**"]
public_api = true
bump_order = 2
post_bump_hooks = [
  "cd b && go get github.com/victormf2/a@{{version}}",
  "cd b && go mod tidy",
  "git add b/go.mod b/go.sum",
]